//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DependancyWithWidgets.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        public int WidgetID { get; set; }
        public string Name { get; set; }
        public decimal BasePrice { get; set; }
        public bool Discount { get; set; }
        public bool ActiveBit { get; set; }
    }
}
